apiVersion: v1
kind: Pod
metadata:
  labels:
    name: maven
spec:
  containers:
  - name: maven
    image: maven:3.6.1-jdk-11-slim
    command:
    - cat
    tty: true
    volumeMounts:
      - name: maven-repo
        mountPath: "/root/.m2/repository"
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: mvn-cache
